### ISSUE TITLE
Support environment variables on containers

### ISSUE THREAD

**Issue by AdrianRossouw** [nearform/nscale#35]
One of the best ways I have found to configure multiple instances of services is to use environment variables, but I haven't found any documentation for configuring them on containers.

Any plans for this feature?

**Comment by AdrianRossouw** [comment]
I know this is closed, and that's a way you could do it... but it feels kind of dodgy to be putting service credentials and the like into version control like this.

**Comment by mcollina** [comment]
I _agree_ with you. However VMs should be completely disposable, with no special treatment, e.g. adding a SSL certificate or a username/password combination by hand is something that we cannot add.

Possible ways to solve this:

1. add support for a `config.js` thing which will contain nscale-specific credentials (AWS, ssh keys and so on) which is not committed into git. There we can add some custom ENV variables to be passed on to containers when started.
2. add an hook system, so that you can copy your data in the VMs _before_ a container is started: we are not doing it, but it can be a plugin etc.

Both might happen at some point in the future. But which one will you prefer?

**Comment by AdrianRossouw** [comment]
I was thinking something more like consul's KV store, that is collated into an env when doing a docker-run. This seems pretty straight forward ...
https://github.com/hashicorp/envconsul

**Comment by AdrianRossouw** [comment]
apparently support for an 'env' property was added to 0.17

**Comment by AdrianRossouw** [comment]
for my current task, i found that putting a .env file on the server directly, and setting up `--env-file /home/nscale/server.env` in the args were the better solution.
