### ISSUE TITLE
Put a system offline

### ISSUE THREAD

**Issue by mcollina** [nearform/nscale#61]
I think by putting a system offline we should commit a new revision with an empty `topology.containers` section, and 'deploy' it.

**Comment by AdrianRossouw** [comment]
This came up because I had a container that I hadn't built correctly, so supervisor was going into an infinite loop trying to start it up, spinning up my fans and using a bunch of processing power.

The only way I could think to stop it was to kill the docker container manually with docker kill.

This kind of problem eludes to the need for health checks and other things that are probably out of scope for nscale right now. I mean, I'd expect it to revert to a previous revision in that case at the very least.

**Comment by mcollina** [comment]
nscale 0.16 has the 'system stop' command.
